### ISSUE TITLE
Selection doesn't show correct size and coordinates

### ISSUE THREAD

**Issue by ademartini** [andrefarzat/ng-jcrop#11]
From what I can see, the size and coordinates bound to 'selection' are relative to the size in the editor image.  Not the actual size of the image.

**Comment by andrefarzat** [comment]
@ademartini I was using and converting the width/height at the server. But I took advantage of https://github.com/andrefarzat/ng-jcrop/pull/10 where @bl0wfish fixed it. I think it's good now. 
Just released the [2.0.0 version](https://github.com/andrefarzat/ng-jcrop/tree/2.0.0) ( major version for it isn't backwards compatible ) 

Also added a [demo page](http://andrefarzat.github.io/ng-jcrop/)

Thanks for reporting :smile_cat:
