### ISSUE TITLE
Change the preview pannel size

### ISSUE THREAD

**Issue by minhlong** [andrefarzat/ng-jcrop#12]
I using your package but i do not know how to change the size of the preview pannel. Can you help me?

Thanks and Best Regards,

**Comment by andrefarzat** [comment]
@minhlong sure. But unfortunately, the preview style is hard coded: https://github.com/andrefarzat/ng-jcrop/blob/master/ng-jcrop.js#L122

Gonna do a PR adding the possibility of changing it =)

**Comment by minhlong** [comment]
@andrefarzat Thanks so much for your informatino ;)

Best Regards,

**Comment by andrefarzat** [comment]
PR open: https://github.com/andrefarzat/ng-jcrop/pull/13
