### ISSUE TITLE
Tried removing thumbnail but remove the main image!

### ISSUE THREAD

**Issue by ja67** [andrefarzat/ng-jcrop#14]
Hi, I tried your plugin for image cropping and it worked well with default settings used in your demo with thumbnail enabled. However, when I set the thumbnail to be "false", the thumbnail didn't disappear but the main image is removed! I checked the source code and found something really confusing in line 282 and 283 of jcrop.js:
`  $scope.thumbnailWrapper = $element.find('.ng-jcrop-image-wrapper');
   $scope.thumbnailWrapper.empty().append($scope.mainImg);`
So actually the thumbnail switch changes the visibility of the main image rather than the thumbnail. I am curious why it  work because when I try to change the **thumbnailWrapper** to correct element, the whole module doesn't work at all. 

Thanks.

**Comment by andrefarzat** [comment]
@ja67 You are completely right and I feel ashamed for NOT have seeing this.
I think this PR solves it. Can I ask you to check it out: https://github.com/andrefarzat/ng-jcrop/pull/15 ?

Thanks a lot for reporting =)
