### ISSUE TITLE
Bower version does not have setPreviewStyle

### ISSUE THREAD

**Issue by lucas-garcia** [andrefarzat/ng-jcrop#16]
Hi André,

I got your plugin from bower and it does not have the setPreviewStyle method. And the one got from npm looks quite different as well. Are they both not up to date? By the way, thanks for the plugin.

**Comment by andrefarzat** [comment]
Hi, @lucas-garcia , I installed via `bower install ng-jcrop` and I've got the current version ( 2.0.1 ), but looks like the npm versions was outdated. Thanks a lot for you tip. I think I solved it =)

**Comment by lucas-garcia** [comment]
Hey @andrefarzat, thanks for the very quick answer. I also got version 2.0.1, but it seems that the code is not the same as the one that is here, because it didn't have the `setPreviewStyle`. Did you check it or you only checked the version that came from bower? Would you mind opening the file and check whether the method is there? Thanks once again for all the support!

**Comment by lucas-garcia** [comment]
Oh, anyway it's fixed now as it is now version 2.0.3! Thanks!

**Comment by andrefarzat** [comment]
Great =)
