### ISSUE TITLE
Get coords in the controller

### ISSUE THREAD

**Issue by lucas-garcia** [andrefarzat/ng-jcrop#17]
Hi André,

After changing the crop selection on the page I want to send the coords to my server so I'll be able to actually crop the real image and save it. But when I try to get the coords, it comes as

`[Infinity, Infinity, Infinity, Infinity, Infinity, Infinity]`

Is there a way to get the actual values?

**Comment by lucas-garcia** [comment]
There is something else I noticed. Line 318 and 320 you're actually hiding the main image, not the thumbnail. So if I set thumbnail option to false it's breaking and showing the wrong elements.

**Comment by andrefarzat** [comment]
@lucas-garcia related to hiding the wrong elements, I merged [the quickfix](https://github.com/andrefarzat/ng-jcrop/pull/15) . Please, update to 2.0.3 =)

Can I ask you to develop more the problem ? The [demo](http://andrefarzat.github.io/ng-jcrop/) (which uses the file in the master branch ) seems ok

**Comment by lucas-garcia** [comment]
@andrefarzat I was setting `maxWidth` and `maxHeight` to `null` and `boxWidth: window.innerWidth - 200`  because I wanted the image to occupy the whole screen. The `shrinkRatio` is calculated dividing `img.width / ngJcropConfig.jcrop.maxWidth` - dividing by null, which was causing `shrinkRatio`to be infinite.

The way I solved it was setting `maxWidth` and `maxHeight` to a very high value like 4000 and it is working now, but I don't know if this is the most elegant way.

**Comment by andrefarzat** [comment]
@lucas-garcia well, it is a simple solution. What we can do is change [this line](https://github.com/andrefarzat/ng-jcrop/blob/master/ng-jcrop.js#L275) to check if `maxWidth/maxHeight` is `null` ( or an invalid value ) and (1)throw an Error or set it to empty ( cleaning the css ).
What do you think ?

**Comment by lucas-garcia** [comment]
I like the idea of cleaning the css, then the image would fit the screen and the `maxWidth` would be its width. 
But what about [these lines](https://github.com/andrefarzat/ng-jcrop/blob/master/ng-jcrop.js#L169)? What value would you set it to?

**Comment by andrefarzat** [comment]
@lucas-garcia for `getShrinkRatio` it would be only `img.width/img.height` without dividing by `maxWidth/maxHeight`. So, there must be a check there too

**Comment by lucas-garcia** [comment]
Sounds very good @andrefarzat!
