### ISSUE TITLE
Demos or exmples of how to display the ng-jcrop image larger

### ISSUE THREAD

**Issue by infomofo** [andrefarzat/ng-jcrop#20]
I'm trying to use the ng-jcrop div in a larger layout but no matter what I do I can't seem to get the div to appear full screen width.  Do you have any examples of applying css to make the entire image appear larger?

**Comment by andrefarzat** [comment]
@infomofo I can create an example and debug it to make it work. Can I ask you direction (or even the code) to make the example ?
