### ISSUE TITLE
Jcrop jQuery plugin not loading

### ISSUE THREAD

**Issue by ewertb** [andrefarzat/ng-jcrop#25]
Hi I have an Angular app. When I run it through uglify the ng-jcrop directive throws an exception saying that the jQuery Jcrop plugin has to be included but I did reference it from my index.html. Note this is only a problem when I minify. Also I am not minifying the Jcrop directive or any of my bower components... This is how I referenced it in my index.html...

````
<script src="bower_components/jquery/dist/jquery.min.js"></script>
<script src="bower_components/jcrop/js/jquery.Jcrop.min.js"></script>
<script src="bower_components/angular/angular.min.js"></script>
<script src="bower_components/ng-jcrop/ng-jcrop.js" type="text/javascript"></script>
````

Can you please help?

**Comment by andrefarzat** [comment]
Hi @ewertb, in a quick test here it seemed to work. Here is the fiddlejs : https://jsfiddle.net/andrefarzat/hf31bna6/2/

Can I ask you to edit it until you reproduce the error ?
Thanks :smile:
