### ISSUE TITLE
ng-jcrop saying `selection` must be an array

### ISSUE THREAD

**Issue by piyushchauhan2011** [andrefarzat/ng-jcrop#27]
Error: ngJcrop: attribute `selection` must be an array

I'm trying to load the ng-jcrop onClick of a button in a `position:absolute` popup window. After clicking the button it appears up with this message in console and doesn't show up anything.

If anyone know how to use ng-jcrop in a hidden window and make it appear on button click, would be very helpful!

and I also tried some other things but it shows up like this:
![screen shot 2015-06-06 at 11 30 52 am](https://cloud.githubusercontent.com/assets/693487/8017654/99f6748c-0c3f-11e5-8790-9e0975c91d19.png)

A funny dot with 0px \* 0px appears in place of image on left hand side.

**Comment by MikeSpoon** [comment]
Hi, 
See the issue I posted (https://github.com/andrefarzat/ng-jcrop/issues/26)
The only workaround I found, is to initialize the jcop component when the popup is visible.
And replacing the following line seems to help too: (but fix not the problem)
old:
$scope.jcrop = jQuery.Jcrop($scope.mainImg, config);
new:
$scope.mainImg.Jcrop(config, function () { $scope.jcrop = this });

hope we all can find the best solution to fix that.

regards
Mike
