### ISSUE TITLE
Update jcrop to 2.0.0

### ISSUE THREAD

**Issue by andrefarzat** [andrefarzat/ng-jcrop#28]
Create the version 3.0.0 of ng-jcrop and update jCrop to 2.0.0 (http://jcrop.org/)

This will close https://github.com/andrefarzat/ng-jcrop/issues/26 and  https://github.com/andrefarzat/ng-jcrop/issues/27

cc @MikeSpoon

**Comment by alexbowers-tecmark** [comment]
any update on this?

**Comment by andrefarzat** [comment]
@alexbowers-tecmark Haven't seen this repo for awhile. Are you in need of this ?

**Comment by alexbowers-tecmark** [comment]
If you have it that'd be great.

if not dont worry, we have reverted to using the jquery plugin for jcrop
and not an angular plugin since it wouldn't work.

Thanks.

**Comment by kelkes** [comment]
+1 would be great if you could update to the latest jcrop version

**Comment by andrefarzat** [comment]
@kelkes I can start having fun with it this weekend =]

**Comment by kelkes** [comment]
Hey @andrefarzat any progress with this?

**Comment by andrefarzat** [comment]
@kelkes I don't think it worth to take time to give support to jcrop 2.x, at least for now.
The project is still in WIP and even the website is not updated/finished : http://jcrop.org/doc/

Are you using 2.x in prod ?

**Comment by adrian2monk** [comment]
The directive still having issues when it used with Jcrop 2.x. It's been a while and now  (Jcrop)[https://github.com/tapmodo/Jcrop] last *tag* is **v.2.0.4** but doesn't work with the latest version of this directive, at least for me :(
