### ISSUE TITLE
Don't use ngShow/ngHide. Use ngIf

### ISSUE THREAD

**Issue by diego-betto** [andrefarzat/ng-jcrop#32]
Don't use ngShow/ngHide in your wrapper or you will end with a 0px box.

Use [ngIf](https://docs.angularjs.org/api/ng/directive/ngIf) since it removes/recreate elements.

>ngIf differs from ngShow and ngHide in that ngIf completely removes and recreates the element in the DOM rather than changing its visibility via the display css property. A common case when this difference is significant is when using css selectors that rely on an element's position within the DOM, such as the :first-child or :last-child pseudo-classes.

**Comment by andrefarzat** [comment]
@diego-betto may I ask you to show me where you've found `ngShow/ngHide` being used ?
I could find only jQuery's show [here](https://github.com/andrefarzat/ng-jcrop/blob/master/ng-jcrop.js#L322) and hide [here](https://github.com/andrefarzat/ng-jcrop/blob/master/ng-jcrop.js#L324).

Please, re open the issue if you found it
