### ISSUE TITLE
Getting the cropped image binary in your url

### ISSUE THREAD

**Issue by zacharynevin** [andrefarzat/ng-jcrop#37]
I am trying to crop an image before uploading it. How can I get the data (base64 url) for the cropped image?

**Comment by andrefarzat** [comment]
Right now, when you add some image from your computer, the code reads it using [readAsDataUrl](https://github.com/andrefarzat/ng-jcrop/blob/master/ng-jcrop.js#L109-L118) and replaces [the `$scope.ngJcrop` value](https://github.com/andrefarzat/ng-jcrop/blob/master/ng-jcrop.js#L343). So, you might be able to see the data source from it.

Let me know if doesn't work, so we can come up with a way to make it work :smiley_cat:

**Comment by aakaashh** [comment]
How do I access $scope.ngJcrop from the controllers?

**Comment by andrefarzat** [comment]
@aakaashh are you talking about the value you pass to the directive ?
```html
<div ng-jcrop="obj.src" selection="obj.coords" thumbnail="obj.thumbnail"></div>
```
if yes, you already have it (hardcoded or not). If you're asking the internal directive scope of ngJcrop, it's not exposed.

**Comment by aakaashh** [comment]
I wanted to get the (base64 url) for the cropped image. Is there a way of getting that?

**Comment by andrefarzat** [comment]
in this line: https://github.com/andrefarzat/ng-jcrop/blob/master/ng-jcrop.js#L124
It is triggered the `JcropChangeSrc` event at the rootScope, so you can listen to it to get the base64 of the whole image. jCrop itself doesn't crop in the browser, so you have the image and the selection data to crop in the server. Unfortunately, it must be done in the server.

See: http://deepliquid.com/content/Jcrop_Implementation_Theory.html

**Comment by aakaashh** [comment]
Okay. Thank a lot.

**Comment by rudolph2907** [comment]
It would be great if you can add it to the docs.

**Comment by andrefarzat** [comment]
@rudolph2907 I added as `FAQ` section: https://github.com/andrefarzat/ng-jcrop#faq

<img width="933" alt="screen shot 2016-10-24 at 4 01 59 pm" src="https://cloud.githubusercontent.com/assets/649219/19657504/3ecf581e-9a03-11e6-8d85-4d98cfa841bb.png">

What do you think ?

**Comment by rudolph2907** [comment]
I've tested an the event doesn't actually fires.

**Comment by peterjunsworth** [comment]
Not taking any credit from this but: https://jsfiddle.net/zm7e0jev/

**Comment by sschadwick** [comment]
@peterjunsworth I would love to see this functionality carried through to ng-jcrop. Our use-case involves off-loading the computation of resizing to the client.
