### ISSUE TITLE
Accidentally using "shade" mode?

### ISSUE THREAD

**Issue by scottybrown** [andrefarzat/ng-jcrop#38]
JCrop has a shade mode whereby the grey area surrounding the crop selection box is made up of 4 grey squares, rather than a second image with opacity set to appear grey. This can be seen in the JCrop Github tutorial 4 as an experimental feature.

ng-jcrop seems to be using shade mode accidentally. It calls jQuery.Jcrop($scope.mainImg, config), but I think it should be passing in $scope.mainImg[0] which has a tagName set to IMG rather than undefined.

Shade mode seems to work okay so the impact is probably negligible for most users. The impact for us is that we're trying to modify the crop selection to be circular instead of square. This is much more difficult in shade mode.

**Comment by andrefarzat** [comment]
@scottybrown I see. You're right for [this line](https://github.com/tapmodo/Jcrop/blob/v0.9.13/js/jquery.Jcrop.js#L299). Working on that

**Comment by andrefarzat** [comment]
@scottybrown PR opened : https://github.com/andrefarzat/ng-jcrop/pull/39
Can I ask you to run the demo and see if it was solved for you ?
Thanks

**Comment by scottybrown** [comment]
Yeah no problem.
I ran the demo and it all seems good. The 3 demos seem to work and definitely aren't using shade mode.
I did get a couple of test failures, not sure if that's something on my end or not.
![screen shot 2015-11-10 at 4 58 28 pm](https://cloud.githubusercontent.com/assets/3635061/11055536/4b0bca3a-87cc-11e5-9044-26d17c2c72f2.png)

**Comment by andrefarzat** [comment]
Nice catch. Haven't played the tests against chrome/firefox. Fixed :smile_cat:

**Comment by andrefarzat** [comment]
Can I get your ok ?

**Comment by scottybrown** [comment]
It seems to be working Chrome, but still makes the first failures on Firefox 42 ("ng-jcrop JcropController getShrinkRatio should return the correct Shrink Ratio")

**Comment by andrefarzat** [comment]
I am making travis-ci to run Firefox in xvfb.
All green in travis-ci https://travis-ci.org/andrefarzat/ng-jcrop :dancer:

**Comment by scottybrown** [comment]
Oh it does seem to be working now in Firefox. Strange. Must have been something on my end.

For the record this is just me running it locally, with no launchers configured, manually traveling to http://localhost:9876/ in Firefox 42.0.0.
All good :+1:

**Comment by andrefarzat** [comment]
Version `2.1.1` published :smiley_cat:
