### ISSUE TITLE
Setting the configs dinamically

### ISSUE THREAD

**Issue by naneri** [andrefarzat/ng-jcrop#41]
Is there any way to make it possible to set the config options dinamically in the controller and not having to create preconfigured presets?

**Comment by andrefarzat** [comment]
@naneri unfortunately no. As it was so seldom having more than one jCrop per page, we have done was creating named config. So, what you can do is to create two or more config options and toggle among them:

```js
app.config(function(ngJcropConfigProvider){

    // Config without a name is the "default" config
    ngJcropConfigProvider.setJcropConfig({
        bgColor: 'black',
        bgOpacity: 0.4,
        aspectRatio: 16 / 9
    });

  // First argument as string set a name in the config
  ngJcropConfigProvider.setJcropConfig("config2", {
        bgColor: 'white',
        bgOpacity: 0.2,
        aspectRatio: 21 / 9
    });

});
```

```html
<!-- This one gets the 'default' config -->
<div ng-jcrop="obj.src" selection="obj.coords" thumbnail="obj.thumbnail"></div>

<!-- This one gets the 'config2' config -->
<div ng-jcrop="obj.src" ng-jcrop-config-name="config2" selection="obj.coords" thumbnail="obj.thumbnail"></div>
```

This was a solution to another person's problem. It doesn't change dynamically, for `ngJcropConfigName` doesn't have a watcher on it.

If this doesn't solve your problem, let's work to improve it or see another solution :smile_cat:

**Comment by woohling** [comment]
Didn't work in my app😥... Still using the first config

**Comment by andrefarzat** [comment]
@woohling can I ask you to show me your code here ?

**Comment by woohling** [comment]
Roughly the same code above, but just failed to work. 😥 
I'm using it in a directive, and it's a little bit complicated to say ..  I gave up eventually ..
