### ISSUE TITLE
Problem with scope.previewImg.show

### ISSUE THREAD

**Issue by Carloospm** [andrefarzat/ng-jcrop#42]
First, Thanks all!

I've tried to install, but i've trouble with : 

TypeError: scope.previewImg.show is not a function
    at Object.fn (ng-jcrop.js:368)
    at r.$digest (angular.min.js:131)
    at r.$apply (angular.min.js:134)
    at g (angular.min.js:87)
    at T (angular.min.js:92)
    at XMLHttpRequest.w.onload (angular.min.js:93)

Look in demo site, check that my libs are differents:
- jQuery JavaScript Library v2.2.0
- jquery.Jcrop.js v0.9.12
- AngularJS v1.4.8 

Whats the problem?

**Comment by andrefarzat** [comment]
@Carloospm I can't see a problem regarding only the difference between the libraries version.
Can I ask you to (1) confirm that you included jQuery before angular and ng-jcrop, and (2) use [jsfiddle](https://jsfiddle.net/) or similar site to show me the files ?

**Comment by andrefarzat** [comment]
If the problem continues/returns, please reopen the issue

**Comment by brosig** [comment]
I know that it's closed and it's an old issue, but just want to comment so maybe it can help some lost soul:
I was with the same problem and it was indeed the order of inclusion of the scripts.
👍
