### ISSUE TITLE
Update selecting

### ISSUE THREAD

**Issue by Micchaleq** [andrefarzat/ng-jcrop#43]
Hi,

I have problem, I want to update selecting ( cords ) from inputs bu I cant.

Would you help me what I schould add / change?

**Comment by andrefarzat** [comment]
Hi, @Micchaleq,
the `selection` attribute is the current coords. So, you can add inputs to it.

Simple example:
```html
<script>
app.controller('SomeController', function($scope){
    $scope.obj = {}

    // The url or the data64 for the image
    $scope.obj.src = 'beautifulImage.jpg';

    // Must be [x, y, x2, y2, w, h]
    $scope.obj.coords = [100, 100, 200, 200, 100, 100];

    // You can add a thumbnail if you want
    $scope.obj.thumbnail = true;
});
</script>

<input type="text" ng-model="obj.coords" ng-list />

<div ng-jcrop="obj.src" selection="obj.coords" thumbnail="obj.thumbnail"></div>
```

So, you could improve to create an input for each of the fields :smile_cat:

**Comment by rickerd** [comment]
I've tried to update the coords trough input fields but the crop is not changing size.

`$scope.obj = {
                src: $scope.user.image.src.$ngfBlobUrl,
                coords: [0, 0, $scope.user.image.width, $scope.user.image.height, $scope.user.image.width, $scope.user.image.height],
                size: {
                    w: $filter('mmtocm')($scope.user.image.width),
                    h: $filter('mmtocm')($scope.user.image.height),
                }
            };`

`<input type="text" class="form-control" id="cropWidth"
                                           data-ng-model="obj.coords[4]" />`

Am i doing something wrong?

**Comment by andrefarzat** [comment]
@rickerd there are no watchers to `obj.selection` as they are considered `readOnly`.
Do you wanna to change the selection area with the input of the user ?

**Comment by rickerd** [comment]
Yes this is what i want. Input that change on drag + update the cropper when i change values.

**Comment by rickerd** [comment]
Im trying to accomplish to have the coords bi-directional but i don't have an solution sadly.

**Comment by andrefarzat** [comment]
@rickerd this is really odd and it is out of the current scope of the code (i.e.: It's not possible as the code is now ).

As a quick solution, how about we implement an event in the `$rootScope` to be triggered and change the current selection? ex:
```js
var coords = {x: 10, y: 10, ... };
var configName = "default";
$rootScope.$emit("jcropSelectionChange", coords, configName);
```

**Comment by rickerd** [comment]
Can you setup a Gitter? its easier to talk over there i think @andrefarzat 
And im trying to change the plugin so you can put in the coords in the directive and only use that and not map it from selection to coords.

I want to put in an object and only work with 1 object. Im not a super great developer in JavaScript or AngularJS but im trying my ultimate best.

**Comment by andrefarzat** [comment]
@rickerd is that what you're trying to reach: http://deepliquid.com/projects/Jcrop/demos.php?demo=advanced ? You type the x, y, x2, y2 and click apply and the image is selected ?

never tried gitter. Let's see: https://gitter.im/andrefarzat/ng-jcrop
