### ISSUE TITLE
Not working with Cloudinary

### ISSUE THREAD

**Issue by benjamincanac** [andrefarzat/ng-jcrop#46]
I tried to use this plugin with the Cloudinary API using the crop mode, but the result is never good.

[http://cloudinary.com/documentation/node_image_manipulation#crop_mode](http://cloudinary.com/documentation/node_image_manipulation#crop_mode)

Have you ever experienced this issue ?

Thanks.

**Comment by andrefarzat** [comment]
@benjamincanac never tried with cloudinary. It might be that jCrop sends an array and cloudinary expects an object with the data to be cropped ? ( I am guessing here, haven't read all the docs )

**Comment by benjamincanac** [comment]
@andrefarzat Cloudinary expects 4 parameters : x / y / width / height. I'm sending the good object using the values in the jCrop array.

I'm sure this is good because it works approximately, with small images it works almost perfectly but bigger the image is, the more the image is shifted.

**Comment by andrefarzat** [comment]
This was the last changed we did here: https://github.com/andrefarzat/ng-jcrop/pull/34
trying to guess again: it can be something related to min/max width and it sends the wrong ratio or wrong width/height ? ( I really dunno what can be happening )

**Comment by benjamincanac** [comment]
Yes but in my case, the image is bigger than the min/max width. 

I also think that the ratio calculated is wrong and it affects all the values because you multiply every value with the ratio.

However, I've quickly looked into your code and for me your ratio algorithm is ok, so I've no idea either.
