### ISSUE TITLE
Changing the config for each instance of the Controller

### ISSUE THREAD

**Issue by aakaashh** [andrefarzat/ng-jcrop#47]
I have four images that need to be cropped and for each image I want to be able to set different Jcrop config parameters like aspectRatio, maxWidth, maxHeight, minSize and maxSize. How would I change these values from inside each controller. Thank you.

**Comment by andrefarzat** [comment]
@aakaashh it's possible to create a config to each controller: https://github.com/andrefarzat/ng-jcrop/issues/41#issuecomment-163250107

Sorry for not having documented it. Will do it soon.

**Comment by aakaashh** [comment]
Thanks for the response. Will be waiting for the updated documentation. Thanks for building this plugin.
