### ISSUE TITLE
Initialising the Image Controllers only after an image is input from the user

### ISSUE THREAD

**Issue by aakaashh** [andrefarzat/ng-jcrop#48]
In the scenario I am using ng-jcrop a user inputs an image. The base 64 url is extracted from the image file and then sent to the image controllers, which is then initialised to $scope.obj.src. Because when the page loads, the $scope.obj.src is empty I get an error "ngJcrop: attribute `selection` is mandatory". How do I ensure that the controller doesn't execute until the user inputs a file? And also, to hide the HTML accompanying the Controller. 

I am a beginner in Angularjs. Thanks for your patience.

**Comment by andrefarzat** [comment]
@aakaashh you can use the `ng-jcrop-input` directive in the `input[type="file"]` to work together with the `ng-jcrop`. Like this:
```html
<input type="file" ng-jcrop-input />
<div ng-jcrop="obj.src" selection="obj.selection" thumbnail="obj.thumbnail"></div>
```

I updated the [demo page](http://andrefarzat.github.io/ng-jcrop/) with an upload example

**Comment by aakaashh** [comment]
Although this would work for most scenarios, my requirement is something different. I want the user to input one image and be able to crop the same image in 4 specified different crop dimensions. Therefore I had created 4 controllers, one for each crop dimension and once the user inputs an image I then broadcasted the image source to all 4 containers. One way that I can think of achieving this objective is to load the controllers with an image from the server and then once the user inputs the image broadcast the image source to all 4 containers. Until the user selects and image the HTML accompanying the controllers would be. This would be a very inelegant solution.

**Comment by andrefarzat** [comment]
@aakaashh thinking fast here,  the only alternative I can see is you get the crop details one each time.
Example: The user select the image, it appears, then the user set the first selection (do the first crop), you create a button like "Save crop 1", and when clicked you save the current selection and chance the button label to "Save crop 2". Then at the end you have the image and the 4 crop details.

You can even play around with the thumbnail code to display the crop 1, crop 2 and so on :smile_cat:

**Comment by aakaashh** [comment]
@andrefarzat Okay. That could be another approach. But thinking about it, it doesn't fit my purpose because dimensions for each crop is fixed and different from each other. Therefore, I would need four different configs to ensure that the user doesn't change the crop dimensions. Which would require 4 different controllers. 

Thanks anyway. Really appreciate you building ng-jcrop. Has been of great help.

**Comment by andrefarzat** [comment]
@aakaashh I see. Well, there isn't a silver bullet. Good luck in your journey to implement it :)
