### ISSUE TITLE
Different Preview Style for different controllers

### ISSUE THREAD

**Issue by aakaashh** [andrefarzat/ng-jcrop#49]
How do I achieve setting different Thumbnail width and height for different controllers? Is there a way to set different setPreviewStyle config for different controllers?

**Comment by andrefarzat** [comment]
@aakaashh yep. The same way you can add different configs:
```js
    ngJcropConfigProvider.setPreviewStyle('configName', {
        'width': '100px',
        'height': '100px',
        'overflow': 'hidden',
        'margin-left': '5px'
    });
```

**Comment by aakaashh** [comment]
Thank you.
