### ISSUE TITLE
NaN/Infinity when maxHeight or maxWidth set

### ISSUE THREAD

**Issue by lizfischer** [andrefarzat/ng-jcrop#53]
Whenever I set maxHeight or maxWidth in the config, all the coords come out either NaN or Infinity. 
Edit: Sorry, just searched. Seems this is the same issue as #17. Was this never fixed?

**Comment by andrefarzat** [comment]
@lizfischer it was supposed to be fixed. Can I ask you to paste here your configuration and tell me the size of the image you tried to crop ?
