### ISSUE TITLE
previewImg cannot be found

### ISSUE THREAD

**Issue by bojan-stankovic** [andrefarzat/ng-jcrop#55]
angular.js:13708 TypeError: scope.previewImg.show is not a function
    at ng-jcrop.js:368
    at Scope.$digest (angular.js:17286)
    at Scope.$apply (angular.js:17552)
    at done (angular.js:11697)
    at completeRequest (angular.js:11903)
    at XMLHttpRequest.requestLoaded (angular.js:11836)

the problem is in the init function on these two lines:
            $scope.imageWrapper = $element.find('.ng-jcrop-image-wrapper');
            $scope.previewImg = $element.find('.ng-jcrop-thumbnail');

I am not sure how this is supposed to work, when this is clearly stated in the angular documentation: find() - Limited to lookups by tag name

More info: [https://docs.angularjs.org/api/ng/function/angular.element](url)

I have solved this problem by changing these two lines to: 
            $scope.imageWrapper = angular.element($element[0].querySelector('.ng-jcrop-image-wrapper'));
            $scope.previewImg = angular.element($element[0].querySelector('.ng-jcrop-thumbnail'));

**Comment by bojan-stankovic** [comment]
also this watch: 

$scope.$watch('thumbnail', function(newValue, oldValue, scope){
            if( scope.thumbnail ){
                scope.previewImg.show();
            } else {
                scope.previewImg.hide();
            }
        });

is also not working

**Comment by andrefarzat** [comment]
The `.find` and `.show` functions are from jQuery, not from `jqLite`. As jCrop depends on jQuery, ng-jcrop takes advantage of it also. Thus, looks like jQuery isn't included or not being used (no idea how). There is a check to be sure that it is there: https://github.com/andrefarzat/ng-jcrop/blob/master/ng-jcrop.js#L86-L88

Could you confirm to me that jQuery is included before angular ?

**Comment by bojan-stankovic** [comment]
It seems this was problem on my side, angular was loaded before jquery. 

Sorry for the inconvenience, and thank you for the swift response.

**Comment by andrefarzat** [comment]
No problem. Good was a simple thing 😸
