### ISSUE TITLE
Webpack and ng-jcrop

### ISSUE THREAD

**Issue by IuriiKryventsov** [andrefarzat/ng-jcrop#56]
Hi! Today i`ve encountered with the next issue:  i've got error in the console ('jQuery isn't included') when i've tried to load ng-jcrop inside my application.
But when i removed this part

```
if( !$window.jQuery ){
            throw new Error("jQuery isn't included");
}
if( !$window.jQuery.Jcrop ){
            throw new Error("Jcrop isn't included");
}
```

all works properly and i haven't any errors. 

I've used ProvidePlugin but it doesn't help. Maybe you have any ideas to solve this problem?

**Comment by andrefarzat** [comment]
hehey, @IuriiKryventsov . This project was done way before browserify and webpack became popular, so these two checks were added to avoid common mistakes of adding jQuery or jCrop after ng-jcrop. And, as this is an angular 1.x package, I avoided to add they as `peerDependency` for usually people ending up concatenating the files (not bundling them).

What I think is happening is that `ng-jcrop` expects the jQuery to be global (i.e. attached to window object) and as you're using webpack, you're including it via `require` which doesn't make it global.

A simple solution might be you use webpack to generate a vendor file with jQuery, jCrop and angular (concatenating them from `node_modules/jQuery/dist/jquery.min.js` for example) and you use the [external webpack's configuration](https://webpack.github.io/docs/library-and-externals.html#examples) to include jQuery and Angular in your bundle

**Comment by ctcosmin** [comment]
Another simple solution is to add jquery and jcrop in `webpack.config` file when specifying the module loaders. 

```
module: {
    loaders: [
      {test: require.resolve('jquery'), loader: 'expose?jQuery!expose?$'},
      {test: require.resolve('jquery-jcrop'), loader: 'expose?jQuery.Jcrop!expose?$'}
    ]
}
```

**Comment by coultonluke** [comment]
Not sure why but this all of a sudden has stopped working for me using the expose config. For anyone looking for how to use it just use `import "jquery-jcrop";` into your file.
