### ISSUE TITLE
Update $scope.obj.src in $http

### ISSUE THREAD

**Issue by tslegaitis** [andrefarzat/ng-jcrop#57]
Hey, 

This is a very nice plugin, works like a charm. The only little issue I came across is updating img src after  successful response. 

I'm using Dropzone to upload images, and then when I receive success promise I want to update the $scope.obj.src. It works fine if the src is empty with this code: [Dropzone Plugin](https://gist.github.com/compact/8118670) 

```
// Dropzone
    $scope.dropzoneConfig = {
        'options': { 
            'url': 'question/hotspot',
            'acceptedFiles' : 'image/*',
            'paramName': "file",
            'parallelUploads': 2,
            'createImageThumbnails': true,
            'autoProcessQueue': true
        },
        'eventHandlers': {
            'sending': function (file, xhr, formData) {

                // Set X-CSRF-TOKEN in Request Headers
                xhr.setRequestHeader('X-CSRF-TOKEN', CSRF_TOKEN);

                // Append data to request sent
                $(".page-loading").removeClass("hidden");
            },
            'success': function (file, response) {

                $scope.$apply(function () {
                    $scope.jCropObj.src = response;
                });

                $(".page-loading").addClass("hidden");
            }
        }
    };
```

But if the src already contains a link it doesnt work.

**Comment by tslegaitis** [comment]
Any help is greatly appreciated :)

**Comment by andrefarzat** [comment]
hello, @tslegaitis , I am glad you like and and also I am sorry for it not being well documented.

There is the `ng-jcrop-input` directive which you can add to `input[type="file"]` that you have in the dropzone. This directive is the one responsible to add the file to the `jCrop` (  via `FileReader` api ). You can find an example in the demo: https://github.com/andrefarzat/ng-jcrop/blob/master/demo/index.html#L207

Hope the directives won't conflict with each other. 😸
