### ISSUE TITLE
the demo url should add a '/' in the end?

### ISSUE THREAD

**Issue by Prasinooo** [andrefarzat/ng-jcrop#59]
![image](https://cloud.githubusercontent.com/assets/7079999/21094536/5952b8c4-c092-11e6-9f89-c11671915fe0.png)

http://127.0.0.1:8067/demo/

cannot open 'http://127.0.0.1:8067/demo' unless add a '/'...

**Comment by andrefarzat** [comment]
@Prasinooo funny, it redirects when I type without the trailing slash.
Even thou, I added it in the `readme.md`. Thank you 😸
