### ISSUE TITLE
Conflict when have multi upload inputs

### ISSUE THREAD

**Issue by ducthang310** [andrefarzat/ng-jcrop#60]
I add two upload inputs on the same page and got an error:
  - When click to any input for choosing a new image
  - Both of them are updated
Please check the below images: 
<img width="447" alt="screen shot 2016-12-16 at 1 11 56 pm" src="https://cloud.githubusercontent.com/assets/3962548/21253485/ae77b870-c391-11e6-95ef-32b820d9a70b.png">
This error is made by below code: 
<img width="591" alt="screen shot 2016-12-16 at 1 10 25 pm" src="https://cloud.githubusercontent.com/assets/3962548/21253497/caf44720-c391-11e6-9e83-fab210e2cabb.png">

"$rootScope.$broadcast" is reason for all upload inputs are changed.
And currently, I have changed the code to: $scope.$broadcast
<img width="609" alt="screen shot 2016-12-16 at 1 10 42 pm" src="https://cloud.githubusercontent.com/assets/3962548/21253534/0b64a642-c392-11e6-878e-52115f6cac09.png">

It's good for me. And I hope it's fine with you.
If this solution is not correct (has some potential bugs). Please help me to check it or fix it.
Thank you so much!
p/s: My english is so bad, I'm so sorry for that :-D

**Comment by andrefarzat** [comment]
hello @ducthang310 , you can see in the demo (http://andrefarzat.github.io/ng-jcrop/) that we have several instances running side by side. It's possible to name a configuration to each case, therefore, you can have these instances behaving individually.

The directive which does that is `ng-jcrop-config-name="configName"`. Please, have a look in the [README.md](https://github.com/andrefarzat/ng-jcrop#usage) 😄

**Comment by ducthang310** [comment]
Hi Andrefarzat,
This issue is still occur when I use ng-jcrop-config-name with different configName,
"$rootScope.$broadcast" is reason for all Upload inputs are changed.
The demo (http://andrefarzat.github.io/ng-jcrop/) has only one Upload input. If you have multi Upload input, you'll see the error.

Thank you for your help!

**Comment by andrefarzat** [comment]
@ducthang310 true. I haven't checked that there are two upload inputs.
Will implement it in the demo page, so I can see it happening here 😃

**Comment by andrefarzat** [comment]
@ducthang310 the demo now is updated with a functional example: http://andrefarzat.github.io/ng-jcrop/
