### ISSUE TITLE
HI, is it possible to set trueSize[w,h] dynamic instead of static in angularjs

### ISSUE THREAD

**Issue by TankBhavik** [andrefarzat/ng-jcrop#62]
Hi i want to set dynamic trueSize[]. Is it possible to set after image upload and uploaded image width,height need to set here.
I have used angularjs

**Comment by andrefarzat** [comment]
Hi @TankBhavik, you can use `ngJcropConfigProvider.setJcropConfig` to set jCrop configuration.
Ex: https://github.com/andrefarzat/ng-jcrop#usage

**Comment by TankBhavik** [comment]
In this case i have set truesize[] from angularController. so how it can possible.

**Comment by andrefarzat** [comment]
@TankBhavik can you show me the code ? 😸

**Comment by TankBhavik** [comment]
okay.

**Comment by TankBhavik** [comment]
Here is my app.config
___________________________________

angular.module('app').config(function ($httpProvider, ngJcropConfigProvider) {
        $httpProvider.defaults.headers.common["X-Requested-With"] = 'XMLHttpRequest';
        $httpProvider.interceptors.push('authInterceptorService');

        ngJcropConfigProvider.setJcropConfig('test', {
            bgColor: 'gray',
            bgOpacity: 0.4,
            trueSize: [2560, 1600],
            //allowSelect: false,
            //allowMove: true,
            //allowResize: false,                                
        });
    });

In here i want to set my original image  trueSize: [width, height] instead of fix value so is it possible ?

Here is my angular control 
________________________________________________________

  .controller('ImageCropController', function ($scope, $mdDialog, $controller, inputs, $filter, CommonFactory, $timeout) {
        $controller('LoadingWaitCtrl', { $scope: $scope });
        $controller('CommonCtrl', { $scope: $scope });

        $scope.ImageData = inputs.dataObj;
        $scope.CropImage = {};
        $scope.obj = {};
        $scope.obj.thumbnail = false;
        $scope.CropImage.ImageName = $scope.ImageData.Image;
        $scope.obj.src = getImageSrc($scope.ImageData.Image);

        function getImageSrc(src) {
            return '/Images/Temp/' + src;
        }

        $scope.cancel = function () {
            $mdDialog.cancel();
        };

        $scope.SaveCropImage = function (data) {

            $scope.CropImage.Xcoordinate = data.selection[0];
            $scope.CropImage.Ycoordinate = data.selection[1];
            $scope.CropImage.Width = data.selection[4];
            $scope.CropImage.Height = data.selection[5];
            $scope.CropImage.ImagePath = data.src;

            var response = CommonFactory.SaveCropImage($scope.CropImage);
            response.success(function (successData, headers, status, config) {
                $scope.ImageData.ThumbnailPath = successData;
                $mdDialog.cancel($scope.ImageData);
            });
        }

        $timeout(function () {
            $scope.ImgCropSrc = $scope.obj.src;
        }, 350);
     })

In this controller i actually want to pass truesize[width,height]. and i have used partial for uploading an image.

**Comment by andrefarzat** [comment]
Hi, @TankBhavik , I added an example in http://andrefarzat.github.io/ng-jcrop/ with the thumbnail working with a `trueSize` config.
At the end, I *think* that jCrop/ngJcrop isn't getting the right selection value related to trueSize, for the idea is to make this math at the server side. Is this the problem you're facing ?

**Comment by rahim-figs** [comment]
@andrefarzat We need to be able to set `trueSize` from the controller, not during initialization, as a config. Is it possible?

**Comment by andrefarzat** [comment]
@rahim-figs as is, you can create different configurations and change them on the fly using `ng-jcrop-config-name` directive
