### ISSUE TITLE
How to consume Jcrop has events like onSelect, onChange and onRelease?

### ISSUE THREAD

**Issue by dreamerNcoder** [andrefarzat/ng-jcrop#63]
Hi, 

Its a good library with basic things available with minimum changes required.

I checked Jcrop and found there are many events like onSelect, onChange and onRelease, And ngJcrop hides those events, which can be very helpfull in consumer to save the cropped image, currently there is no way to get the cropped image from ngJcrop?

Thanks.

**Comment by andrefarzat** [comment]
Hello, @dreamerNcoder,

The image is cropped at the server side, not in Jcrop code. Jcrop only submits the image and the coords and the server does the cropping ([check the manual here](http://deepliquid.com/content/Jcrop_Implementation_Theory.html)).
Related to the events. Usually they aren't necessary, once ng-jcrop intents to be an angular wrapper for Jcrop, you can get the coords via `$scope.obj.coords` (see the [example](https://github.com/andrefarzat/ng-jcrop#usage)).

You can check the [demo examples](http://andrefarzat.github.io/ng-jcrop/) using the `obj.coords` (like this: https://github.com/andrefarzat/ng-jcrop/blob/master/demo/index.html#L202-L207).

Hope it was helpful 😸

**Comment by dreamerNcoder** [comment]
Ok, so basically the cropping will happen based on the coordinated on server side. Correct?

**Comment by andrefarzat** [comment]
Exactly! 😸 

If you need more help, please re-open the issue
