### ISSUE TITLE
`npm install ng-jcrop --save` fails on brand new project.

### ISSUE THREAD

**Issue by infloop** [andrefarzat/ng-jcrop#65]
Hi.

After creating a brand new project with `npm init` and then `npm install ng-jcrop --save` I got the following error:

```
ng-jcrop@2.2.0 postinstall E:\github\ng-jcrop-test\node_modules\ng-jcrop
bower install

'bower' is not recognized as an internal or external command,
operable program or batch file.
```

You have a `postinstall`  script `bower install`, but bower is included in `devDependencies` and is not installed by normal npm install. Also, bower is not installed globally on my machine.

I'm using webpack for my project and bower will be not included in my package.json and will not be installed globally.

I suggest removing `bower install` from `postinstall` scripts.

**Comment by andrefarzat** [comment]
hi @infloop . Thanks for reporting it.
I moved the `bower install` to `prestart`. Which means it will be executed only when `npm start` is ran.
`npm install ng-jcrop --save` is now working :smile_cat:

**Comment by infloop** [comment]
Thanks!
